### ISSUE TITLE
OS icon show linux even OSX

### ISSUE THREAD

**Issue by renatosuero** [hoob3rt/lualine.nvim#120]
the OS icon doesn't work, I think file format isn't the best option to get the OS. I don't know the best, I only know using **has** vim function. I've tried and it looks good.
I'd like to know what do you think @hoob3rt 
PS. Mac/OSX needs to be first because it also return 1 to has('unix')
PS. I have a change [here](https://github.com/renatosuero/lualine.nvim/commit/367ee067a0855c0ce9ff984ab18946bbecd8b530) I didn't create the PR because first I'd like to know about you 
![Screenshot 2021-02-26 at 23 32 08](https://user-images.githubusercontent.com/1093214/109362230-d9cf6600-788a-11eb-8c0a-addfb2bbf0ae.png)

**Comment by shadmansaleh** [comment]
I think you've got the idea of fileformat wrong. Fileformat component doesn't indecate which os you're using vim on .It indecates which charecter ends line <LN> or <CR> or both . It's there because . Todays major OSes failed to agree on how basic txt format works .

From vim helppages:
> 'fileformat' 'ff'	string (Windows default: "dos",
				Unix default: "unix",
				Macintosh default: "mac")
			local to buffer
	This gives the <EOL> of the current buffer, which is used for
	reading/writing the buffer from/to a file:
	    dos	    <CR> <NL>
	    unix    <NL>
	    mac	    <CR>
	When "dos" is used, CTRL-Z at the end of a file is ignored.
	See |file-formats| and |file-read|.
	For the character encoding of the file see 'fileencoding'.
	When 'binary' is set, the value of 'fileformat' is ignored, file I/O
	works like it was set to "unix".
	This option is set automatically when starting to edit a file and
	'fileformats' is not empty and 'binary' is off.
	When this option is set, after starting to edit a file, the 'modified'
	option is set, because the file would be different when written.
	This option cannot be changed when 'modifiable' is off.

You can checkout https://vim.fandom.com/wiki/File_format . Also you can search online for <LN> and <CR> online if you wana know more.

**Comment by renatosuero** [comment]
My bad , shame on me 😂 thanks @shadmansaleh
