### ISSUE TITLE
Create integration with wilder.nvim

### ISSUE THREAD

**Issue by gennaro-tedesco** [hoob3rt/lualine.nvim#142]
[wilder.nvim](https://github.com/gelguy/wilder.nvim) is a nice plugin that enhances the statusline experience; in particular it draws `SEARCH` and `COMMAND` displays on the statusline when invoked: would it be possible to extend `lualine.nvim` to integrate with it (I have noticed that at the moment when invoking search or commands the lualine defaults to no colours/no theme)?

**Comment by hoob3rt** [comment]
> [wilder.nvim](https://github.com/gelguy/wilder.nvim) is a nice plugin that enhances the statusline experience

It has nothing to do with the statusline. It only affects wildmenu.

>  in particular it draws `SEARCH` and `COMMAND` displays on the statusline when invoked

As I've said. The plugin you are refering to does not change the statusline. The `COMMAND` mode is displayed properly by lualine. The `SEARCH` mode does not exist in vim (it is still command mode). The plugin author simply puts a string in front when performing a search

> I have noticed that at the moment when invoking search or commands the lualine defaults to no colours/no theme?

You are experiencing "no theme" because wilder.nvim draws wildmenu where the statusline is instead of a popup (neovim default).

> would it be possible to extend lualine.nvim to integrate with it

Possible? Probably but I don't want to integrate with it.
